### ISSUE TITLE
Meta XML needs to be updated

### ISSUE THREAD

**Issue by DavidOliver** [symphonists/entry_url_field#7]
This extension seems to work okay with Sym 2.6. I'm not sure exactly how the meta XML should be updated; is it okay to update the version numbers (max?) of the last release node?

**Comment by nitriques** [comment]
Hey David,

The way I've been doing it is by creating a new version.

Since this is a feature, I would add

```xml
<release version="1.4.0" date="2016-03-03" min="2.3.x" max="2.x.x"><![CDATA[
	* Marked as compatible with Symphony 2.x.x
]]>
</release>
```

Thanks!

**Comment by DavidOliver** [comment]
I see - thanks.

As it's not functionally different, might it be cleaner to merely add a `max` attribute to the last release?

    <release version="1.3.0" date="2012-06-21" min="2.3.x">

    <release version="1.3.0" date="2012-06-21" min="2.3.x" max="2.x.x">

Then again, this would mean that a file (extension.meta.xml) had changed within the single release, which I suppose is technically something to avoid.

**Comment by nitriques** [comment]
> As it's not functionally different, might it be cleaner to merely add a max attribute to the last release?

The extension site won't pick it up...

> which I suppose is technically something to avoid.

Not necessarily. Version numbers are for computer.

**Comment by nitriques** [comment]
The meta file has been updated.
